Vector = Vector or require("resources/lib/vector")
-- screen-related variables
SCREEN_WIDTH = love.graphics.getWidth()
SCREEN_HEIGHT = love.graphics.getHeight()
HALF_WIDTH = SCREEN_WIDTH / 2
HALF_HEIGHT = SCREEN_HEIGHT / 2
ZERO_WIDTH, ZERO_HEIGHT = 0, 0

-- grid class variables
-- vertical lines
FIRST_VLINE_X1 = HALF_WIDTH - 300
FIRST_VLINE_Y1 = ZERO_HEIGHT
FIRST_VLINE_X2 = FIRST_VLINE_X1
FIRST_VLINE_Y2 = SCREEN_HEIGHT

SECOND_VLINE_X1 = HALF_WIDTH
SECOND_VLINE_Y1 = ZERO_HEIGHT
SECOND_VLINE_X2 = SECOND_VLINE_X1
SECOND_VLINE_Y2 = SCREEN_HEIGHT

THIRD_VLINE_X1 = HALF_WIDTH + 300
THIRD_VLINE_Y1 = ZERO_HEIGHT
THIRD_VLINE_X2 = THIRD_VLINE_X1
THIRD_VLINE_Y2 = SCREEN_HEIGHT
-- horizontal lines
FIRST_HLINE_X1 = ZERO_WIDTH
FIRST_HLINE_Y1 = HALF_HEIGHT - 300
FIRST_HLINE_X2 = SCREEN_WIDTH
FIRST_HLINE_Y2 = HALF_HEIGHT - 300

SECOND_HLINE_X1 = ZERO_WIDTH
SECOND_HLINE_Y1 = HALF_HEIGHT
SECOND_HLINE_X2 = SCREEN_WIDTH
SECOND_HLINE_Y2 = HALF_HEIGHT

THIRD_HLINE_X1 = ZERO_WIDTH
THIRD_HLINE_Y1 = HALF_HEIGHT + 300
THIRD_HLINE_X2 = SCREEN_WIDTH
THIRD_HLINE_Y2 = HALF_HEIGHT + 300

-- player class variables
TOP_LEFT = Vector.new(660, 240)
TOP_MIDDLE = Vector.new(960, 240)
TOP_RIGHT = Vector.new(1260, 240)
MIDDLE_LEFT = Vector.new(660, 540)
MIDDLE_MID = Vector.new(960, 540)
MIDDLE_RIGHT = Vector.new(1260, 540)
BOTTOM_LEFT = Vector.new(660, 840)
BOTTOM_MIDDLE = Vector.new(960, 840)
BOTTOM_RIGHT = Vector.new(1260, 840)
PLAYER_POSITION_INCREMENT = 300
PLAYER_ROTATION = 0
PLAYER_ROTATION_SPEED = 2
PLAYER_IMAGE_PATH = "resources/images/player/player1.png"

-- enemy class variables
ENEMY_DIRECTION_DOWN = Vector.new(0, 1)
ENEMY_DIRECTION_UP = Vector.new(0, -1)
ENEMY_DIRECTION_LEFT = Vector.new(-1, 0)
ENEMY_DIRECTION_RIGHT = Vector.new(1, 0)
ENEMY_ROTATION_180 = 3.14159

-- enemy square variables
ENEMY_SQUARE_IMAGE_PATH = "resources/images/enemies/animatedSquare.png"
ENEMY_SQUARE_DEFAULT_POSITION = Vector.new(HALF_WIDTH, - 204)
ENEMY_SQUARE_DEFAULT_SPEED = 500
ENEMY_SQUARE_QUAD_WIDTH = 395
ENEMY_SQUARE_QUAD_HEIGHT = 408

-- enemy arrow variables
ENEMY_ARROW_IMAGE_PATH = "resources/images/enemies/animatedArrow.png"
ENEMY_ARROW_DOWN_IMAGE_PATH = "resources/images/enemies/animatedArrow Down.png"
ENEMY_ARROW_DEFAULT_SPEED = 400
ENEMY_ARROW_QUAD_WIDTH = 114
ENEMY_ARROW_QUAD_HEIGHT = 642

ENEMY_ARROW_DEFAULT_POSITION_UP_LEFT = Vector.new( 0 - 114 / 2 - 600 - 600, 642 / 2)
ENEMY_ARROW_DEFAULT_POSITION_UP_MIDDLE = Vector.new(0 - 114 / 2 - 600, 642 / 2)
ENEMY_ARROW_DEFAULT_POSITION_UP_RIGHT = Vector.new(0 - 114 / 2, 642 / 2)

-- enemy rectangle fill variables
ENEMY_RECTANGLE_FILL_IMAGE_PATH = "resources/images/enemies/rectangleFill.png"
ENEMY_RECTANGLE_FILL_DEFAULT_SPEED = 300
ENEMY_RECTANGLE_FILL_QUAD_WIDTH = 135
ENEMY_RECTANGLE_FILL_QUAD_HEIGHT = 1080
ENEMY_RECTANGLE_FILL_LEFT_POSITION = Vector.new(-ENEMY_RECTANGLE_FILL_QUAD_WIDTH / 2, ENEMY_RECTANGLE_FILL_QUAD_HEIGHT / 2)
ENEMY_RECTANGLE_FILL_RIGHT_POSITION = Vector.new(SCREEN_WIDTH + ENEMY_RECTANGLE_FILL_QUAD_WIDTH / 2, ENEMY_RECTANGLE_FILL_QUAD_HEIGHT / 2 )



